name: publish package to pub.dev
on:
  push:
    tags:
      - 'v*'
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup credentials
      run: |
        mkdir -p ~/.pub-cache
        cat <<EOF > ~/.pub-cache/credentials.json
        {
          "accessToken":"${{ secrets.OAUTH_ACCESS_TOKEN }}",
          "refreshToken":"${{ secrets.OAUTH_REFRESH_TOKEN }}",
          "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
          "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
          "expiration": 1616261793933
        }
        EOF
      - name: Publish package
        run: pub publish -f
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_note: ${{ github.ref }}
